### ISSUE TITLE
Omero.table issues

### ISSUE THREAD

**Issue by dominikl** [ome/omero-server#129]
Not sure if omero-server repository is the right place, move if necessary.

Some issues with Omero.tables:
- The supported data types are kind of arbitrary:  https://docs.openmicroscopy.org/omero-blitz/5.5.8/javadoc/omero/grid/Column.html E. g. Why is there a `DoubleColumn`, but no `FloatColumn` (but there is a `FloatArrayColumn`)? 
- There is a `DatasetColumn`, however it doesn't seem to work. Trying to create a Table with DatasetColumn I get:
```
Caused by: omero.InternalException
    serverStackTrace = "Traceback (most recent call last):
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/util/decorators.py", line 69, in exc_handler
                            rv = func(*args, **kwargs)
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/util/decorators.py", line 29, in handler
                            return func(*args, **kwargs)
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/tables.py", line 274, in initialize
                            self.storage.initialize(cols)
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/util/decorators.py", line 91, in with_lock
                            return func(*args, **kwargs)
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/hdfstorageV2.py", line 94, in flush_after
                            return func(*args, **kwargs)
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/hdfstorageV2.py", line 366, in initialize
                            self.__definition = columns2definition(cols)
                          File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/columns.py", line 50, in columns2definition
                            instance = column.descriptor(pos=i)
                        AttributeError: 'DatasetColumn' object has no attribute 'descriptor'
                        "
```

**Comment by joshmoore** [comment]
Think the current questions can be on omero-py.

> * Why is there a `DoubleColumn`, but no `FloatColumn` (but there is a `FloatArrayColumn`)?

Pretty sure this is because when mixing Java/Python/PostgreSQL data types there was no use with one of the column types. Everything got converted _somewhere_ to the maximal width.

> * Trying to create a Table with DatasetColumn I get:

Seems like a pretty straight-forward bug.
