### ISSUE TITLE
Potential PostgreSQL 12 issue

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-server#130]
see: https://www.openmicroscopy.org/qa2/qa/feedback/30334

```
ome.services.query.QueryException: Illegal query:
select distinct experimenter.id,
experimenter.omeName,
experimenter.firstName,
experimenter.lastName,
experimenter.email
from Experimenter experimenter
join experimenter.groupExperimenterMap gem
where experimenter.id = :id
and gem.parent.id in :ids

unexpected token: : near line 10, column 30 [
select distinct experimenter.id,
experimenter.omeName,
experimenter.firstName,
experimenter.lastName,
experimenter.email
from ome.model.meta.Experimenter experimenter
join experimenter.groupExperimenterMap gem
where experimenter.id = :id
and gem.parent.id in :ids
]
at ome.services.query.StringQuery.buildQuery(StringQuery.java:83)
at ome.services.query.Query.doInHibernate(Query.java:222)
at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
```

**Comment by joshmoore** [comment]
Definitely up for closing it ;)
