### ISSUE TITLE
Can't find the LDAP information

### ISSUE THREAD

**Issue by dominikl** [ome/omero-server#133]
See [QA 30583](https://www.openmicroscopy.org/qa2/qa/feedback/30583/)
```
java.lang.Exception: omero.gateway.exception.DSOutOfServiceException: Can't find the LDAP information.
omero.ApiUsageException
    serverStackTrace = "ome.conditions.ApiUsageException: Cannot find unique user DistinguishedName: found=0 (rdbusomjo)
                        	at ome.logic.LdapImpl.mapUserName(LdapImpl.java:201)
                        	at ome.logic.LdapImpl.findExperimenter(LdapImpl.java:174)
                        	at ome.logic.LdapImpl.findDN(LdapImpl.java:162)
                        	at ome.logic.LdapImpl.lookupLdapAuthExperimenter(LdapImpl.java:706)
                        	at ome.logic.AdminImpl.lookupLdapAuthExperimenter(AdminImpl.java:345)
...
```

**Comment by joshmoore** [comment]
see also: https://github.com/ome/omero-web/issues/23
