### ISSUE TITLE
Error when running omero db script -f $OMERODIR/db.sql --password "$OMERO_ROOT_PASS"

### ISSUE THREAD

**Issue by catweis** [ome/omero-server#147]
Following the omero-installation script (for ubuntu 18) I got the following error message, when running " omero db script -f $OMERODIR/db.sql --password "$OMERO_ROOT_PASS" ":

_omero db script -f $OMERODIR/db.sql --password "$OMERO_ROOT_PASS"
Traceback (most recent call last):
  File "/opt/omero/server/venv3/bin/omero", line 118, in <module>
    rv = omero.cli.argv()
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/cli.py", line 1754, in argv
    cli.invoke(args[1:])
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/cli.py", line 1187, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/cli.py", line 1264, in onecmd
    self.execute(line, previous_args)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/cli.py", line 1346, in execute
    args.func(args)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/install/windows_warning.py", line 26, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/plugins/db.py", line 310, in script
    db_vers = self._lookup("version", defaults, args)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/plugins/db.py", line 108, in _lookup
    vdef = defaults.properties.getProperty(propname)
AttributeError: 'NoneType' object has no attribute 'properties'_

From this message, I can unfortunately not see where my error is or what is missing.

**Comment by joshmoore** [comment]
Hi @catweis. Just to be on the safe side:
 - You are installing the latest version of OMERO and
 - `$OMERODIR` points to your OMERO.server installation directory?

What does `_omero config parse` show?

**Comment by catweis** [comment]
Thank you for your fast response.
I am trying to install the latest version for Ubuntu 20.04.
$OMERODIR points to the directory.
_omero config parse shows the same output.

**Comment by joshmoore** [comment]
> $OMERODIR points to the directory.

Can you show me the contents? I'm particular interested in the `etc/` directory which should contain the config files that `_omero config` and `_omero db` are expecting.

**Comment by catweis** [comment]
Thank you again for your fast response. I found that there was a problem with importing the settings.env at installing omero with root. Now, at least this step works for me.

**Comment by joshmoore** [comment]
:+1:
