### ISSUE TITLE
Race conditions and bugs with `ome.services.util.Executor`

### ISSUE THREAD

**Issue by chris-allan** [ome/omero-server#154]
# Background

Over the past several months we've had a few installations that would partially deadlock from time to time. Usually the same phenotype: underlying server looks completely idle, users cannot perform certain actions (login to OMERO.web, `BlitzGateway` logout, import, etc.), and a server restart clears things up. Similar to #125 but we discounted this because for all installations of OMERO Plus `PixelData-0` is disabled.

# Detailed analysis

On Jan 18th we had a customer installation that would deadlock again immediately on OMERO.server restart. After many very painful restart and `jstack` loops later we kept coming up with scenarios where the `ome.services.util.Executor` threads were all consumed but waiting. The threads looked like this:

```
...
"pool-1-thread-1" #30 prio=5 os_prio=0 cpu=178.27ms elapsed=272.44s tid=0x00007fc9d0002800 nid=0x73dd in Object.wait()  [0x00007fca4440c000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.17/Object.java:328)
        at IceInternal.AsyncResultI.__wait(AsyncResultI.java:271)
        - waiting to re-lock in wait() <0x000000054750af58> (a IceInternal.OutgoingAsync)
        at omero.api.IRenderingSettingsPrxHelper.end_resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2705)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2581)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2568)
        at ome.formats.OMEROMetadataStoreClient.resetDefaultsAndGenerateThumbnails(OMEROMetadataStoreClient.java:2416)
        at ome.services.blitz.repo.ManagedImportRequestI.generateThumbnails(ManagedImportRequestI.java:732)
        at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:527)
...
"pool-1-thread-2" #31 prio=5 os_prio=0 cpu=209.38ms elapsed=272.43s tid=0x00007fc9d0003800 nid=0x73de in Object.wait()  [0x00007fca4410b000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.17/Object.java:328)
        at IceInternal.AsyncResultI.__wait(AsyncResultI.java:271)
        - waiting to re-lock in wait() <0x00000005474b1f90> (a IceInternal.OutgoingAsync)
        at omero.api.IRenderingSettingsPrxHelper.end_resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2705)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2581)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2568)
        at ome.formats.OMEROMetadataStoreClient.resetDefaultsAndGenerateThumbnails(OMEROMetadataStoreClient.java:2416)
        at ome.services.blitz.repo.ManagedImportRequestI.generateThumbnails(ManagedImportRequestI.java:732)
        at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:527)
...
"pool-1-thread-3" #32 prio=5 os_prio=0 cpu=175.65ms elapsed=272.39s tid=0x00007fc9d0009000 nid=0x73df in Object.wait()  [0x00007fc9dabfd000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.17/Object.java:328)
        at IceInternal.AsyncResultI.__wait(AsyncResultI.java:271)
        - waiting to re-lock in wait() <0x0000000547563f20> (a IceInternal.OutgoingAsync)
        at omero.api.IRenderingSettingsPrxHelper.end_resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2705)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2581)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2568)
        at ome.formats.OMEROMetadataStoreClient.resetDefaultsAndGenerateThumbnails(OMEROMetadataStoreClient.java:2416)
        at ome.services.blitz.repo.ManagedImportRequestI.generateThumbnails(ManagedImportRequestI.java:732)
        at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:527)
...
"pool-1-thread-4" #33 prio=5 os_prio=0 cpu=206.79ms elapsed=272.36s tid=0x00007fc9d0007000 nid=0x73e0 in Object.wait()  [0x00007fc9daafc000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.17/Object.java:328)
        at IceInternal.AsyncResultI.__wait(AsyncResultI.java:271)
        - waiting to re-lock in wait() <0x00000005475bcee8> (a IceInternal.OutgoingAsync)
        at omero.api.IRenderingSettingsPrxHelper.end_resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2705)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2581)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2568)
        at ome.formats.OMEROMetadataStoreClient.resetDefaultsAndGenerateThumbnails(OMEROMetadataStoreClient.java:2416)
        at ome.services.blitz.repo.ManagedImportRequestI.generateThumbnails(ManagedImportRequestI.java:732)
        at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:527)
...
"pool-1-thread-5" #47 prio=5 os_prio=0 cpu=627.48ms elapsed=271.36s tid=0x00007fc9d000a000 nid=0x73fb in Object.wait()  [0x00007fca45cd4000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.17/Object.java:328)
        at IceInternal.AsyncResultI.__wait(AsyncResultI.java:271)
        - waiting to re-lock in wait() <0x0000000547400670> (a IceInternal.OutgoingAsync)
        at omero.api.IRenderingSettingsPrxHelper.end_resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2705)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2581)
        at omero.api.IRenderingSettingsPrxHelper.resetDefaultsInSet(IRenderingSettingsPrxHelper.java:2568)
        at ome.formats.OMEROMetadataStoreClient.resetDefaultsAndGenerateThumbnails(OMEROMetadataStoreClient.java:2416)
        at ome.services.blitz.repo.ManagedImportRequestI.generateThumbnails(ManagedImportRequestI.java:732)
        at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:527)
...
```

as well as several...

```
...
"Blitz-0-Ice.ThreadPool.Server-1" #37 prio=5 os_prio=0 cpu=891.18ms elapsed=271.81s tid=0x00007fcada169800 nid=0x73e4 waiting on condition  [0x00007fc9da4f5000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.17/Native Method)
        - parking to wait for  <0x00000005472592d8> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.17/LockSupport.java:194)
        at java.util.concurrent.FutureTask.awaitDone(java.base@11.0.17/FutureTask.java:447)
        at java.util.concurrent.FutureTask.get(java.base@11.0.17/FutureTask.java:190)
        at ome.services.util.Executor$Impl.get(Executor.java:509)
        at ome.services.pixeldata.PixelDataThread.onApplicationEvent(PixelDataThread.java:354)
        at ome.services.pixeldata.PixelDataThread.onApplicationEvent(PixelDataThread.java:51)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
...
```

Like the situation @joshmoore took from @erickmartins's post on image.sc this left us scratching our heads as to how this deadlock was happening. One thing was clear:

* The thumbnail generation phase of server side import consumes worker threads at `USER` priority. If enough server side import jobs are in flight (5 is enough, `omero.threads.min_threads` defaults to 5) and __all__ do not have pyramids included with the original data Spring application events will be raised and the server will deadlock. This deadlock occurs because the Spring application event handler in `ome.services.pixeldata.PixelDataThread#onApplicationEvent()` attempts to use the main `ExecutorI` thread pool to perform `PIXELDATA` `EventLog` creation.

This is similar to the issues @joshmoore addressed with the `BACKGROUND` priority and separate thread pool in ome/openmicroscopy#5839.

Further investigation lead us to question why new threads were not being spawned as `omero.threads.max_threads` defaults to 50. We think this comes from a misunderstanding in the original implementation added over 10 years ago in ome/openmicroscopy@aa36c6fbc952cf533d26f31ae6cedbd3609cda53. In short, an unbounded `LinkedBlockingQueue` is used with the `ThreadPoolExecutor` and this results in the maximum number of threads being ignored, creating a situation where the minimum is actually the maximum. This behaviour is consistent with the JDK documentation [^1] on the subject. Specifically:

> Unbounded queues. Using an unbounded queue (for example a [LinkedBlockingQueue](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/LinkedBlockingQueue.html) without a predefined capacity) will cause new tasks to wait in the queue when all corePoolSize threads are busy. Thus, no more than corePoolSize threads will ever be created. (And the value of the maximumPoolSize therefore doesn't have any effect.) This may be appropriate when each task is completely independent of others, so tasks cannot affect each others execution; for example, in a web page server. While this style of queuing can be useful in smoothing out transient bursts of requests, it admits the possibility of unbounded work queue growth when commands continue to arrive on average faster than they can be processed.

We have tasks that __are__ dependent on others and a relatively low `corePoolSize` specified by `omero.threads.min_threads`. That's a recipe for trouble. As coded `omero.threads.max_threads` currently does nothing.

# Path forward

At a minimum, having 5 jobs that trigger other dependent tasks and affect each others execution is bad. We can probably address this for `ome.services.pixeldata.PixelDataThread#onApplicationEvent()` by having the executor submission happen at the `SYSTEM` priority. This will use a dedicated thread pool which as far as I can tell only the `SessionManager` currently uses. Likely all instances where tasks are submitted to the server wide executor should be reviewed for dependency and priority.

The `omero.threads.min_threads` and `omero.threads.max_threads` need to be reviewed and some recommendations made on a path forward. Should we just remove `omero.threads.max_threads`? It basically hasn't worked for over 10 years. Should we set `omero.threads.min_threads` to 50? Was that the intention all along? The JVM concurrency ecosystem has changed a lot in the last 10 years, is there something better we should be using?

Thanks to @emilroz, @erindiel, @DavidStirling and @stick for all the help getting to the bottom of this issue.

/cc @kkoz, @sbesson, @jburel

[^1]: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html

**Comment by joshmoore** [comment]
🤯 

> Was that the intention all along?

Not IIRC.
