### ISSUE TITLE
NPE from AdminImpl.addGroups

### ISSUE THREAD

**Issue by mtbc** [ome/omero-server#69]
```
Wrapped Exception: (java.lang.NullPointerException):
null
at ome.model.meta.Experimenter$1.next(Experimenter.java:450)
at ome.model.meta.Experimenter$1.next(Experimenter.java:437)
at ome.model.meta.Experimenter.linkedExperimenterGroupList(Experimenter.java:491)
at sun.reflect.GeneratedMethodAccessor1339.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:198)
at ome.model.meta.Experimenter_$$_javassist_162.linkedExperimenterGroupList(Experimenter_$$_javassist_162.java)
at ome.security.auth.SimpleRoleProvider.addGroups(SimpleRoleProvider.java:191)
at ome.logic.AdminImpl.addGroups(AdminImpl.java:755)
...
```
- https://github.com/ome/openmicroscopy/blob/475a7fea/components/server/src/ome/logic/AdminImpl.java#L755
- https://www.openmicroscopy.org/qa2/qa/feedback/28063/
- https://www.openmicroscopy.org/qa2/qa/feedback/28064/
- https://www.openmicroscopy.org/qa2/qa/feedback/28065/

See also #65.

**Comment by mtbc** [comment]
Should https://github.com/ome/openmicroscopy/blob/475a7fea/components/dsl/resources/ome/dsl/object.vm#L1122 also check `it.hasNext()`? Or could we have an actually null `link` in the list of `GroupExperimenterMap`?

**Comment by mtbc** [comment]
@joshmoore explains,

> The problem is that the long standing administrators have "gaps" in their list of groups, which is throwing the NullPointerException.
