### ISSUE TITLE
investigate full-text indexer stall

### ISSUE THREAD

**Issue by mtbc** [ome/omero-server#98]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/393/ failed with,
```
org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [ome.model.roi.Roi#21]
	at org.hibernate.impl.SessionFactoryImpl$2.handleEntityNotFound(SessionFactoryImpl.java:435) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:233) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:285) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:152) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:1090) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.impl.SessionImpl.internalLoad(SessionImpl.java:1038) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:630) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.type.EntityType.resolve(EntityType.java:438) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.engine.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:139) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:982) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:857) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2542) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2271) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:459) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:365) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1268) ~[hibernate-core.jar:3.6.10.Final]
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102) ~[hibernate-core.jar:3.6.10.Final]
	at ome.services.fulltext.FullTextIndexer2.index(FullTextIndexer2.java:547) ~[omero-server.jar:5.5.7-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:265) ~[spring-core.jar:4.3.22.RELEASE]
```
Could #73 be at fault?

**Comment by joshmoore** [comment]
Urguh. Worrisome! I would say that blocks the release of the latest omero-server, no?

**Comment by mtbc** [comment]
Let's say so for now.
